name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use Node.js version 16

    - name: Install dependencies
      run: npm ci
      working-directory: frontend  # Set working directory to the 'frontend' directory

    - name: Build the project
      run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
      working-directory: frontend  # Set working directory to the 'frontend' directory

  deploy:
    needs: build  # Ensure that the build step runs first
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Azure client ID
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Azure tenant ID
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Azure client secret
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure subscription ID

    - name: Set up Azure Publish Profile
      uses: Azure/webapps-deploy@v2
      with:
        app-name: "AskWenBot2"  # Azure app name (replace with your app's name)
        publish-profile: ${{ secrets.AZUREAPP_SERVICE_PUBLISHPROFILE }}  # Azure publish profile secret
        package: ./frontend  # Path to your frontend build directory
